name: uid
description: Generate a unique ID from datetime, convert it to millisecondsSinceEpoch,
 and combine it with a random position and a string.
version: 0.1.1
repository: https://github.com/phalsopheak/uid
issue_tracker: https://github.com/phalsopheak/uid/issues


environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


